"""Generate data/words.js with a curated 500-word SpellQuest pool."""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

WORDS = {
    "starter": [
        ("cat", "a small pet animal"),
        ("dog", "a loyal pet animal"),
        ("sun", "the star that lights the day"),
        ("moon", "the bright light in the night sky"),
        ("book", "pages you read"),
        ("pen", "tool used for writing"),
        ("ball", "a round toy you throw"),
        ("tree", "a tall plant with a trunk"),
        ("fish", "an animal that lives in water"),
        ("bird", "an animal with wings that flies"),
        ("home", "the place where you live"),
        ("hand", "part of the body with fingers"),
        ("milk", "white drink from cows"),
        ("cake", "sweet dessert for birthdays"),
        ("rain", "water falling from clouds"),
        ("snow", "soft white ice from the sky"),
        ("star", "a bright point in the night sky"),
        ("frog", "a small green jumping animal"),
        ("duck", "a bird that swims"),
        ("goat", "a farm animal with horns"),
        ("lamp", "something that gives light"),
        ("desk", "a table for writing"),
        ("door", "you open this to enter a room"),
        ("park", "a green place to play outside"),
        ("ship", "a large boat"),
        ("flag", "cloth that shows a country"),
        ("king", "a male ruler"),
        ("queen", "a female ruler"),
        ("apple", "a round fruit"),
        ("grape", "a small fruit that grows in bunches"),
        ("bread", "food made from flour"),
        ("chair", "you sit on this"),
        ("clock", "tells you the time"),
        ("cloud", "white shapes in the sky"),
        ("dress", "clothing often worn by girls"),
        ("earth", "the planet we live on"),
        ("fairy", "a tiny magical being"),
        ("grass", "green plants on the ground"),
        ("happy", "feeling joy"),
        ("juice", "a drink from fruit"),
        ("kite", "a toy that flies on a string"),
        ("lemon", "a sour yellow fruit"),
        ("mouse", "a small animal or computer tool"),
        ("night", "the time when it is dark"),
        ("ocean", "a very large sea"),
        ("paint", "colored liquid for art"),
        ("quiet", "making little or no sound"),
        ("river", "water that flows to the sea"),
        ("smile", "a happy look on your face"),
        ("train", "vehicles that run on tracks"),
        ("uncle", "brother of a parent"),
        ("violin", "a musical string instrument"),
        ("water", "clear liquid we drink"),
        ("yellow", "the color of the sun"),
        ("zebra", "an animal with black and white stripes"),
        ("brave", "not afraid"),
        ("clean", "not dirty"),
        ("dance", "to move to music"),
        ("eagle", "a large strong bird"),
        ("family", "people related to you"),
        ("garden", "a place where plants grow"),
        ("honey", "sweet food made by bees"),
        ("island", "land with water all around"),
        ("jungle", "a thick forest"),
        ("kitten", "a baby cat"),
        ("ladder", "steps you climb"),
        ("magic", "power that seems impossible"),
        ("nurse", "a person who cares for the sick"),
        ("orange", "a round citrus fruit"),
        ("pencil", "tool for writing and drawing"),
        ("rabbit", "a soft animal with long ears"),
        ("school", "a place where you learn"),
        ("tiger", "a big striped wild cat"),
        ("under", "below something"),
        ("voice", "the sound you make when speaking"),
        ("window", "glass that lets light into a room"),
        ("young", "not old"),
        ("animal", "a living creature that is not a plant"),
        ("butter", "soft yellow food from milk"),
        ("candle", "wax stick that burns for light"),
        ("doctor", "a person who helps sick people"),
        ("eleven", "the number after ten"),
        ("flower", "the colorful part of a plant"),
        ("guitar", "a musical instrument with strings"),
        ("helmet", "hard hat that protects your head"),
        ("insect", "a small creature with six legs"),
        ("jacket", "clothing worn over a shirt"),
        ("kitchen", "room where food is cooked"),
        ("little", "small in size"),
        ("mother", "a female parent"),
        ("number", "a symbol used for counting"),
        ("octopus", "a sea animal with eight arms"),
        ("purple", "a color between red and blue"),
        ("question", "something you ask to learn"),
        ("rocket", "a vehicle that flies into space"),
        ("sister", "a girl who shares your parents"),
        ("turtle", "an animal with a hard shell"),
        ("umbrella", "used to stay dry in the rain"),
        ("village", "a small town"),
        ("winter", "the cold season"),
        ("sunny", "full of sunshine"),
        ("funny", "causing laughter"),
        ("penny", "a small coin"),
        ("candy", "sweet treat"),
        ("puppy", "a baby dog"),
        ("teddy", "a soft toy bear"),
        ("bunny", "a rabbit"),
        ("banana", "a long yellow fruit"),
        ("carrot", "an orange root vegetable"),
        ("donkey", "a farm animal like a small horse"),
        ("elephant", "a very large animal with a trunk"),
        ("feather", "soft covering of a bird"),
        ("giant", "very large"),
        ("hammer", "a tool for hitting nails"),
        ("igloo", "a house made of snow"),
        ("jolly", "cheerful and happy"),
        ("kangaroo", "an animal that hops and has a pouch"),
        ("muffin", "a small cake"),
        ("noodle", "a long thin pasta"),
        ("onion", "a vegetable that can make you cry"),
        ("pillow", "soft cushion for your head"),
        ("quilt", "a warm bed cover"),
        ("robot", "a machine that can move and work"),
        ("scooter", "a small vehicle you push with one foot"),
        ("tomato", "a red fruit used in cooking"),
        ("unicorn", "a magical horse with one horn"),
        ("father", "a male parent"),
        ("brother", "a boy who shares your parents"),
        ("circle", "a round shape"),
        ("square", "a shape with four equal sides"),
    ],
    "builder": [
        ("bright", "full of light"),
        ("friend", "someone you like and trust"),
        ("strong", "having power"),
        ("listen", "to pay attention to sound"),
        ("write", "to form words on paper"),
        ("speak", "to talk out loud"),
        ("learn", "to gain knowledge"),
        ("study", "to spend time learning"),
        ("answer", "a reply to a question"),
        ("believe", "to think something is true"),
        ("careful", "paying close attention"),
        ("change", "to make something different"),
        ("decide", "to make a choice"),
        ("early", "before the usual time"),
        ("famous", "known by many people"),
        ("gentle", "kind and soft"),
        ("honest", "telling the truth"),
        ("invite", "to ask someone to join"),
        ("journey", "a long trip"),
        ("kindness", "being friendly and caring"),
        ("library", "a place with many books"),
        ("measure", "to find the size of something"),
        ("nature", "the outdoor world of plants and animals"),
        ("opinion", "what someone thinks"),
        ("patient", "able to wait calmly"),
        ("quality", "how good something is"),
        ("respect", "to treat someone with honor"),
        ("science", "study of how the world works"),
        ("trouble", "a problem or difficulty"),
        ("useful", "helpful for a purpose"),
        ("wonder", "a feeling of amazement"),
        ("across", "from one side to the other"),
        ("balance", "to keep steady"),
        ("certain", "sure about something"),
        ("danger", "a chance of harm"),
        ("effort", "hard work toward a goal"),
        ("future", "the time still to come"),
        ("gather", "to collect things together"),
        ("history", "the story of the past"),
        ("imagine", "to picture in your mind"),
        ("justify", "to give a good reason"),
        ("knowledge", "facts and information you know"),
        ("language", "words people use to communicate"),
        ("mystery", "something hard to explain"),
        ("notice", "to see or become aware"),
        ("ordinary", "common and usual"),
        ("protect", "to keep safe from harm"),
        ("quickly", "at a fast speed"),
        ("remember", "to keep something in mind"),
        ("special", "better or different from usual"),
        ("tonight", "this coming night"),
        ("unusual", "not common"),
        ("valuable", "worth a lot"),
        ("weather", "the condition of the air outside"),
        ("excited", "very happy and eager"),
        ("because", "for the reason that"),
        ("beautiful", "very pleasing to look at"),
        ("complete", "finished with nothing missing"),
        ("different", "not the same"),
        ("example", "something that shows how"),
        ("favorite", "liked the most"),
        ("important", "having great meaning"),
        ("possible", "able to be done"),
        ("probably", "likely to happen"),
        ("suddenly", "happening without warning"),
        ("together", "with each other"),
        ("although", "even though"),
        ("between", "in the middle of two things"),
        ("continue", "to keep going"),
        ("describe", "to tell what something is like"),
        ("enough", "as much as needed"),
        ("forward", "toward the front"),
        ("however", "but on the other hand"),
        ("include", "to make part of a group"),
        ("instead", "in place of something else"),
        ("nothing", "not anything"),
        ("perhaps", "maybe"),
        ("receive", "to get something given to you"),
        ("several", "more than two but not many"),
        ("through", "from one end to the other"),
        ("whether", "if it is true that"),
        ("already", "before now"),
        ("another", "one more"),
        ("around", "on all sides"),
        ("behind", "at the back of"),
        ("during", "throughout a period of time"),
        ("finally", "at the end"),
        ("himself", "that man or boy"),
        ("itself", "that thing alone"),
        ("myself", "I; me personally"),
        ("nobody", "no person"),
        ("outside", "not inside"),
        ("people", "human beings"),
        ("should", "ought to"),
        ("someone", "a person"),
        ("though", "even if"),
        ("toward", "in the direction of"),
        ("always", "at all times"),
        ("almost", "nearly"),
        ("before", "earlier than"),
        ("better", "of higher quality"),
        ("cannot", "is not able to"),
        ("country", "a nation"),
        ("follow", "to go after"),
        ("happen", "to take place"),
        ("period", "a length of time"),
        ("problem", "something difficult to solve"),
        ("reason", "a cause or explanation"),
        ("result", "what happens because of something"),
        ("second", "the unit after first"),
        ("system", "a set of connected parts"),
        ("thought", "an idea in the mind"),
        ("without", "not having"),
        ("against", "in opposition to"),
        ("appear", "to come into view"),
        ("become", "to turn into"),
        ("brought", "past of bring"),
        ("caught", "past of catch"),
        ("choose", "to pick from options"),
        ("common", "shared by many"),
        ("create", "to make something new"),
        ("effect", "a result of a cause"),
        ("energy", "power to do work"),
        ("except", "not including"),
        ("expect", "to think something will happen"),
        ("express", "to show a feeling or idea"),
        ("figure", "a number or shape"),
        ("further", "to a greater extent"),
        ("general", "applying to most cases"),
        ("ground", "the surface of the earth"),
        ("growth", "the process of getting larger"),
        ("letter", "a written message or alphabet mark"),
        ("matter", "something important"),
        ("method", "a way of doing something"),
        ("middle", "the center point"),
        ("minute", "sixty seconds"),
        ("modern", "of the present time"),
        ("moment", "a very short time"),
        ("motion", "movement"),
        ("nation", "a country and its people"),
        ("natural", "found in nature"),
        ("object", "a thing you can touch"),
        ("office", "a place for work"),
        ("spelling", "the way letters form words"),
        ("reading", "looking at and understanding words"),
        ("writing", "putting words on paper"),
        ("teacher", "a person who helps you learn"),
        ("student", "a person who learns"),
        ("chapter", "a main part of a book"),
        ("sentence", "a group of words with meaning"),
        ("paragraph", "a group of sentences"),
        ("dictionary", "a book of word meanings"),
        ("syllable", "a beat in a spoken word"),
        ("absence", "being away"),
        ("accident", "an unexpected harmful event"),
        ("address", "where a person lives"),
        ("adventure", "an exciting experience"),
        ("argument", "a disagreement with reasons"),
        ("audience", "people watching a performance"),
        ("average", "the usual amount"),
        ("awkward", "uncomfortable or clumsy"),
        ("baggage", "bags taken when traveling"),
        ("behavior", "the way someone acts"),
        ("benefit", "something that helps"),
        ("bicycle", "a two-wheeled vehicle"),
        ("calendar", "a chart of days and months"),
        ("caption", "words that explain a picture"),
        ("capture", "to catch or take"),
        ("career", "a persons long-term work"),
        ("cartoon", "a funny drawing or show"),
        ("ceiling", "the top inside surface of a room"),
        ("century", "one hundred years"),
        ("courage", "bravery in facing fear"),
        ("curious", "eager to learn or know"),
        ("delight", "great pleasure"),
        ("examine", "to look at carefully"),
        ("freedom", "the power to act freely"),
        ("genuine", "real and sincere"),
        ("harmony", "peaceful agreement"),
        ("improve", "to make better"),
        ("justice", "fair treatment"),
        ("loyalty", "faithfulness to someone"),
    ],
    "challenger": [
        ("necessary", "needed; required"),
        ("separate", "to set apart"),
        ("conscience", "inner sense of right and wrong"),
        ("rhythm", "a regular repeated pattern of sound"),
        ("accommodate", "to provide space or help for"),
        ("embarrass", "to make someone feel awkward"),
        ("privilege", "a special right or advantage"),
        ("maintenance", "the work of keeping something working"),
        ("occurrence", "something that happens"),
        ("recommend", "to suggest as good"),
        ("definitely", "without any doubt"),
        ("environment", "the natural world around us"),
        ("government", "the system that rules a country"),
        ("independent", "free from control by others"),
        ("opportunity", "a chance for progress"),
        ("particularly", "especially; more than usually"),
        ("responsibility", "duty to deal with something"),
        ("temperature", "how hot or cold something is"),
        ("unfortunately", "sadly; in a way that is bad"),
        ("achievement", "something done successfully"),
        ("appreciate", "to value or be grateful for"),
        ("communicate", "to share information"),
        ("competition", "a contest between people"),
        ("consequence", "a result of an action"),
        ("development", "growth or progress"),
        ("experience", "knowledge from doing things"),
        ("immediately", "at once; without delay"),
        ("information", "facts or details"),
        ("interesting", "holding your attention"),
        ("magnificent", "extremely beautiful or impressive"),
        ("organization", "a group with a purpose"),
        ("performance", "how well something is done"),
        ("preparation", "getting ready beforehand"),
        ("relationship", "the way people are connected"),
        ("significant", "important; meaningful"),
        ("successful", "achieving a desired result"),
        ("understanding", "ability to grasp meaning"),
        ("vocabulary", "all the words a person knows"),
        ("enthusiastic", "full of eager interest"),
        ("extraordinary", "very unusual or remarkable"),
        ("indispensable", "absolutely necessary"),
        ("perseverance", "continued effort despite difficulty"),
        ("pronunciation", "the way a word is spoken"),
        ("sophisticated", "complex or highly developed"),
        ("spontaneous", "done without planning"),
        ("sufficient", "enough for the need"),
        ("transparent", "see-through; open and clear"),
        ("unbelievable", "hard to accept as true"),
        ("unforgettable", "impossible to forget"),
        ("abbreviation", "a shortened form of a word"),
        ("acceleration", "increase in speed"),
        ("accidentally", "by chance; not on purpose"),
        ("acknowledge", "to accept or admit"),
        ("acquaintance", "someone you know slightly"),
        ("advantageous", "helpful; beneficial"),
        ("aggressive", "ready to attack or argue"),
        ("ambiguous", "having more than one meaning"),
        ("anniversary", "a yearly celebration of a date"),
        ("anonymous", "without a known name"),
        ("appropriate", "suitable for the situation"),
        ("approximately", "roughly; about"),
        ("architecture", "the design of buildings"),
        ("artificial", "made by humans; not natural"),
        ("assessment", "judgment of value or quality"),
        ("assignment", "a task given to someone"),
        ("assistance", "help given to someone"),
        ("atmosphere", "the air around the Earth"),
        ("attendance", "being present at an event"),
        ("attitude", "a way of thinking or feeling"),
        ("authority", "power to give orders"),
        ("available", "able to be used or obtained"),
        ("awareness", "knowledge that something exists"),
        ("beginning", "the start of something"),
        ("beneficial", "producing good results"),
        ("biography", "a written life story"),
        ("boundary", "a dividing line"),
        ("brilliant", "very bright or very clever"),
        ("calculator", "a device that does math"),
        ("campaign", "organized action toward a goal"),
        ("candidate", "a person seeking a position"),
        ("capacity", "the amount something can hold"),
        ("category", "a group of similar things"),
        ("celebrate", "to mark a happy event"),
        ("cemetery", "a place where the dead are buried"),
        ("challenge", "a difficult task"),
        ("character", "moral qualities of a person"),
        ("circumstance", "a fact or condition of a situation"),
        ("colleague", "a person you work with"),
        ("combination", "things joined together"),
        ("commercial", "related to business"),
        ("commission", "a fee or official group"),
        ("commitment", "a promise to do something"),
        ("committee", "a group chosen for a task"),
        ("community", "people living in one area"),
        ("comparison", "looking at similarities and differences"),
        ("compassion", "care for others who suffer"),
        ("competence", "ability to do something well"),
        ("complaint", "an expression of dissatisfaction"),
        ("complex", "made of many connected parts"),
        ("complicate", "to make more difficult"),
        ("component", "a part of a larger whole"),
        ("composition", "something created, such as writing"),
        ("comprehensive", "including nearly everything"),
        ("compromise", "an agreement with give and take"),
        ("concentrate", "to focus attention"),
        ("concept", "an idea or principle"),
        ("concern", "worry or interest about something"),
        ("conclude", "to decide after thinking"),
        ("concrete", "real and solid; not abstract"),
        ("condition", "the state of something"),
        ("conduct", "behavior; or to lead"),
        ("conference", "a formal meeting"),
        ("confidence", "belief in yourself or others"),
        ("confirm", "to make sure something is true"),
        ("conflict", "a serious disagreement"),
        ("confusion", "a lack of clear understanding"),
        ("persuasion", "the act of convincing someone"),
        ("dedication", "strong commitment to a task"),
        ("motivation", "reason for acting"),
        ("inspiration", "something that sparks ideas"),
        ("celebration", "a joyful gathering"),
        ("explanation", "making something clear"),
        ("exploration", "travel to discover"),
        ("imagination", "the ability to form mental pictures"),
        ("observation", "careful watching"),
        ("presentation", "showing work to an audience"),
        ("accelerate", "to speed up"),
        ("accessible", "easy to reach or use"),
        ("accomplish", "to succeed in doing"),
        ("accuracy", "correctness"),
        ("accusation", "a claim that someone did wrong"),
        ("adaptation", "a change to fit a new situation"),
        ("adequate", "good enough"),
        ("admiration", "respect and liking"),
        ("admission", "permission to enter; or confessing"),
        ("adolescent", "a young person becoming an adult"),
        ("advertise", "to promote a product"),
        ("ambitious", "having a strong desire to succeed"),
        ("eloquent", "fluent and persuasive in speech"),
    ],
    "elite": [
        ("pneumonia", "a serious lung infection"),
        ("bureaucracy", "a system of many official rules"),
        ("conscientious", "careful and thorough in duty"),
        ("entrepreneur", "a person who starts a business"),
        ("fluorescent", "giving off bright light"),
        ("idiosyncrasy", "a strange personal habit"),
        ("liaison", "a person who connects groups"),
        ("maneuver", "a skilled movement or plan"),
        ("millennium", "a period of one thousand years"),
        ("miscellaneous", "made up of mixed kinds"),
        ("onomatopoeia", "words that imitate sounds"),
        ("parliament", "a group that makes laws"),
        ("reconnaissance", "exploration to gather information"),
        ("restaurateur", "a person who owns a restaurant"),
        ("sacrilegious", "disrespectful toward sacred things"),
        ("surveillance", "close watching of someone"),
        ("unnecessarily", "more than is needed"),
        ("zucchini", "a green summer squash vegetable"),
        ("acquiesce", "to accept without protest"),
        ("aesthetic", "concerned with beauty"),
        ("bourgeois", "middle-class in style or values"),
        ("camaraderie", "friendly trust among people"),
        ("chiaroscuro", "use of light and dark in art"),
        ("dachshund", "a short-legged long-bodied dog"),
        ("ecclesiastical", "related to the church"),
        ("facetious", "treating serious things lightly"),
        ("garrulous", "talking too much"),
        ("hierarchy", "a ranked system of levels"),
        ("incontrovertible", "impossible to deny"),
        ("juxtaposition", "placing things side by side for contrast"),
        ("kaleidoscope", "a tube of shifting colored patterns"),
        ("labyrinthine", "like a maze; complicated"),
        ("metamorphosis", "a complete change of form"),
        ("nomenclature", "a system of names"),
        ("obsequious", "overly eager to please"),
        ("pharmaceutical", "related to medicines"),
        ("quixotic", "unrealistically idealistic"),
        ("renaissance", "a rebirth of art and learning"),
        ("soliloquy", "a speech spoken alone on stage"),
        ("triskaidekaphobia", "fear of the number thirteen"),
        ("ubiquitous", "found everywhere"),
        ("vicissitude", "a change of fortune"),
        ("whimsical", "playfully unusual"),
        ("xenophobia", "fear or dislike of foreigners"),
        ("zealous", "full of eager energy"),
        ("abysmal", "extremely bad"),
        ("belligerent", "hostile and aggressive"),
        ("clandestine", "kept secret"),
        ("dilapidated", "falling apart from age"),
        ("ephemeral", "lasting a very short time"),
        ("furtive", "secretive; sneaky"),
        ("gregarious", "fond of company"),
        ("harangue", "a long angry speech"),
        ("immutable", "unable to be changed"),
        ("jubilant", "full of great joy"),
        ("laconic", "using very few words"),
        ("mellifluous", "sweet-sounding"),
        ("nefarious", "wicked or criminal"),
        ("ostentatious", "showy in a flashy way"),
        ("perspicacious", "having sharp insight"),
        ("querulous", "complaining a lot"),
        ("recalcitrant", "stubbornly resisting control"),
        ("sanguine", "cheerfully hopeful"),
        ("truculent", "fierce and aggressive"),
        ("unctuous", "excessively flattering"),
        ("vociferous", "loud and forceful"),
        ("wheedle", "to coax with flattery"),
        ("abstemious", "not self-indulgent"),
        ("bombastic", "using pompous language"),
        ("cacophony", "harsh unpleasant noise"),
        ("deleterious", "causing harm"),
        ("equivocate", "to speak unclearly on purpose"),
        ("fastidious", "very hard to please"),
        ("grandiloquent", "using lofty language"),
        ("hegemony", "leadership or dominance"),
        ("iconoclast", "a person who attacks traditions"),
        ("jingoistic", "extreme patriotic aggression"),
        ("lugubrious", "looking or sounding sad"),
        ("machination", "a secret plot"),
        ("nonchalant", "calm and unconcerned"),
        ("obfuscate", "to make unclear"),
        ("perfidious", "deceitful and untrustworthy"),
        ("quintessential", "the perfect example of something"),
        ("reprehensible", "deserving strong criticism"),
        ("sesquipedalian", "using long words"),
        ("taciturn", "reserved; saying little"),
        ("anachronism", "something out of its proper time"),
        ("antithesis", "the direct opposite"),
        ("apocryphal", "of doubtful truth"),
        ("archetype", "an original model"),
        ("ascetic", "practicing severe self-discipline"),
        ("assiduous", "showing great care and effort"),
        ("auspicious", "showing signs of future success"),
        ("autonomous", "self-governing"),
        ("pulchritudinous", "physically beautiful"),
        ("psycholinguistics", "study of language and the mind"),
    ],
    "open": [
        ("articulate", "able to express ideas clearly"),
        ("resilient", "able to recover quickly"),
        ("diligent", "showing care and steady effort"),
        ("integrity", "honesty and strong moral principles"),
        ("empathy", "understanding another persons feelings"),
        ("innovative", "introducing new ideas"),
        ("strategic", "carefully planned for a goal"),
        ("collaborate", "to work with others"),
        ("negotiate", "to discuss and reach agreement"),
        ("synthesize", "to combine parts into a whole"),
        ("critique", "a careful judgment"),
        ("hypothesis", "a testable explanation"),
        ("paradigm", "a typical model or pattern"),
        ("rhetoric", "the art of persuasive speaking"),
        ("discourse", "formal discussion of a topic"),
        ("advocacy", "public support for a cause"),
        ("facilitate", "to make a process easier"),
        ("implement", "to put a plan into action"),
        ("evaluate", "to judge the value of something"),
        ("coherent", "logical and consistent"),
        ("concise", "clear and brief"),
        ("nuance", "a subtle difference in meaning"),
        ("pragmatic", "dealing with things practically"),
        ("meticulous", "showing great attention to detail"),
        ("tenacious", "holding firmly to a goal"),
        ("versatile", "able to adapt to many uses"),
        ("initiative", "the ability to start things independently"),
        ("accountability", "responsibility for outcomes"),
        ("transparency", "openness and clarity"),
        ("stakeholder", "a person with interest in a project"),
        ("benchmark", "a standard for comparison"),
        ("deliverable", "a finished product owed to others"),
        ("milestone", "an important point in progress"),
        ("framework", "a basic supporting structure"),
        ("methodology", "a system of methods"),
        ("infrastructure", "basic systems serving a community"),
        ("sustainability", "ability to continue long-term"),
        ("entrepreneurship", "the activity of starting businesses"),
        ("globalization", "increasing worldwide connection"),
        ("demographic", "related to population groups"),
        ("algorithm", "a step-by-step problem-solving process"),
        ("database", "an organized collection of data"),
        ("interface", "a point where systems meet"),
        ("prototype", "an early model of a product"),
        ("iteration", "a repeated cycle of improvement"),
        ("oratory", "the art of public speaking"),
        ("diction", "clearness of speech"),
        ("elocution", "skill in clear public speaking"),
        ("impromptu", "done without preparation"),
        ("authenticity", "the quality of being genuine"),
        ("calibration", "precise adjustment of a tool"),
        ("capability", "power or ability to do something"),
        ("catalyst", "something that causes change"),
        ("coherence", "logical connection"),
        ("compliance", "following rules"),
    ],
}

TARGETS = {
    "starter": 100,
    "builder": 140,
    "challenger": 120,
    "elite": 90,
    "open": 50,
}

TRACK_ORDER = ["starter", "builder", "challenger", "elite", "open"]

DIFFICULTY = {
    "starter": 1,
    "builder": 2,
    "challenger": 3,
    "elite": 5,
    "open": 4,
}


def build() -> list[dict]:
    seen: set[str] = set()
    by_track: dict[str, list[dict]] = {t: [] for t in TRACK_ORDER}
    for track in TRACK_ORDER:
        for word, definition in WORDS[track]:
            key = word.lower().strip()
            if key in seen:
                continue
            seen.add(key)
            by_track[track].append(
                {
                    "word": key,
                    "definition": definition,
                    "track": track,
                    "difficulty": DIFFICULTY[track],
                }
            )

    final: list[dict] = []
    for track in TRACK_ORDER:
        subset = by_track[track]
        if len(subset) < TARGETS[track]:
            raise SystemExit(f"{track} has only {len(subset)}, need {TARGETS[track]}")
        final.extend(subset[: TARGETS[track]])
    return final


def main() -> None:
    pool = build()
    counts = Counter(item["track"] for item in pool)
    print("total", len(pool), dict(counts))
    out_dir = Path(__file__).parent / "data"
    out_dir.mkdir(exist_ok=True)
    js_path = out_dir / "words.js"
    payload = json.dumps(pool, indent=2)
    js_path.write_text(
        f"window.SPELLQUEST_WORDS = {payload};\n",
        encoding="utf-8",
    )
    print("wrote", js_path)


if __name__ == "__main__":
    main()
